name: Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/docker-ci-cd-demo:latest .

      - name: Run tests
        run: docker run --rm your-dockerhub-username/docker-ci-cd-demo:latest python -m unittest discover -s tests

      - name: Push Docker image
        run: docker push your-dockerhub-username/docker-ci-cd-demo:latest